[package]
name = "hello_from_rust"
version = "0.1.0"
authors = ["OscarClemente <oscar.clemente@gmail.com>"]
edition = "2018"

[lib]
crate-type =["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
